spring:
  application:
    name: workspace-api

  profiles:
    active: local

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

workspace:
  jwt:
    secret: ${WORKSPACE_JWT_SECRET}
    access-token-expiration-seconds: 3600