CREATE TABLE WORKSPACE_USER (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR),
    USER_NAME VARCHAR2(100 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_WORKSPACE_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_WORKSPACE_USER_EMAIL UNIQUE (EMAIL)
);