CREATE TABLE MEMO_FOLDER (
    FOLDER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID NUMBER NOT NULL,
    FOLDER_NAME VARCHAR2(100 CHAR) NOT NULL,
    IS_SYSTEM CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_MEMO_FOLDER
        PRIMARY KEY (FOLDER_ID),

    CONSTRAINT FK_MEMO_FOLDER_USER
        FOREIGN KEY (USER_ID)
        REFERENCES WORKSPACE_USER (USER_ID)
        ON DELETE CASCADE,

    CONSTRAINT CK_MEMO_FOLDER_IS_SYSTEM
        CHECK (IS_SYSTEM IN ('Y', 'N')),

    CONSTRAINT UK_MEMO_FOLDER_USER_NAME
        UNIQUE (USER_ID, FOLDER_NAME)
);

CREATE INDEX IX_MEMO_FOLDER_USER_ID
    ON MEMO_FOLDER (USER_ID);

