CREATE TABLE MEMO (
    MEMO_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FOLDER_ID NUMBER NOT NULL,
    TITLE VARCHAR2(255 CHAR),
    CONTENT CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_MEMO
        PRIMARY KEY (MEMO_ID),

    CONSTRAINT FK_MEMO_FOLDER
        FOREIGN KEY (FOLDER_ID)
            REFERENCES MEMO_FOLDER (FOLDER_ID)
            ON DELETE CASCADE,

    CONSTRAINT UK_MEMO_FOLDER_MEMO
        UNIQUE (FOLDER_ID, MEMO_ID)
);

CREATE INDEX IX_MEMO_FOLDER_UPDATED
    ON MEMO (FOLDER_ID, UPDATED_AT DESC);