CREATE TABLE BOARD_NODE (
    MEMO_ID NUMBER,
    POSITION_X NUMBER NOT NULL,
    POSITION_Y NUMBER NOT NULL,
    STACK_ORDER NUMBER DEFAULT 0 NOT NULL,

     CONSTRAINT PK_BOARD_NODE
          PRIMARY KEY (MEMO_ID),

     CONSTRAINT FK_BOARD_NODE_MEMO
         FOREIGN KEY (MEMO_ID)
         REFERENCES MEMO (MEMO_ID)
         ON DELETE CASCADE,

     CONSTRAINT CK_BOARD_NODE_STACK_ORDER
         CHECK (STACK_ORDER >= 0)
);