CREATE TABLE BOARD_EDGE (

    EDGE_ID NUMBER
        GENERATED ALWAYS AS IDENTITY,

    FOLDER_ID NUMBER NOT NULL,
    SOURCE_MEMO_ID NUMBER NOT NULL,
    TARGET_MEMO_ID NUMBER NOT NULL,
    EDGE_TYPE VARCHAR2(30 CHAR) DEFAULT 'RELATED' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_BOARD_EDGE
        PRIMARY KEY (EDGE_ID),

    CONSTRAINT FK_BOARD_EDGE_SOURCE
        FOREIGN KEY (FOLDER_ID, SOURCE_MEMO_ID)
        REFERENCES MEMO (FOLDER_ID, MEMO_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_BOARD_EDGE_TARGET
        FOREIGN KEY (FOLDER_ID, TARGET_MEMO_ID)
        REFERENCES MEMO (FOLDER_ID, MEMO_ID)
        ON DELETE CASCADE,

    CONSTRAINT CK_BOARD_EDGE_DIFFERENT_MEMO
        CHECK (SOURCE_MEMO_ID <> TARGET_MEMO_ID),

    CONSTRAINT CK_BOARD_EDGE_TYPE
        CHECK (
        EDGE_TYPE IN (
            'RELATED',
            'CAUSE',
            'REFERENCE',
            'CONTRADICTS',
            'SEQUENCE'
            )
        ),

    CONSTRAINT UK_BOARD_EDGE_CONNECTION
        UNIQUE (
             FOLDER_ID,
             SOURCE_MEMO_ID,
             TARGET_MEMO_ID,
             EDGE_TYPE
             )
);

CREATE INDEX IX_BOARD_EDGE_TARGET
    ON BOARD_EDGE (FOLDER_ID, TARGET_MEMO_ID);